// <auto-generated />
using System;
using Gateway.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gateway.Api.Data.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260808120000_RemoveLeaderLease")]
    partial class RemoveLeaderLease
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gateway.Api.Data.DeployHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("FromDigest")
                        .HasColumnType("text")
                        .HasColumnName("from_digest");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ToDigest")
                        .HasColumnType("text")
                        .HasColumnName("to_digest");

                    b.HasKey("Id");

                    b.ToTable("deploy_history", (string)null);
                });

            modelBuilder.Entity("Gateway.Api.Data.DeployInstanceStatus", b =>
                {
                    b.Property<int>("DeployId")
                        .HasColumnType("integer")
                        .HasColumnName("deploy_id");

                    b.Property<string>("InstanceId")
                        .HasColumnType("text")
                        .HasColumnName("instance_id");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DeployId", "InstanceId");

                    b.ToTable("deploy_instance_status", (string)null);
                });

            modelBuilder.Entity("Gateway.Api.Data.InstanceStatus", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("text")
                        .HasColumnName("instance_id");

                    b.Property<string>("GatewayVer")
                        .HasColumnType("text")
                        .HasColumnName("gateway_ver");

                    b.Property<DateTimeOffset>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heartbeat_at");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("boolean")
                        .HasColumnName("is_leader");

                    b.Property<string>("PrivateIp")
                        .HasColumnType("text")
                        .HasColumnName("private_ip");

                    b.Property<string>("PublicIp")
                        .HasColumnType("text")
                        .HasColumnName("public_ip");

                    b.Property<string>("Services")
                        .HasColumnType("jsonb")
                        .HasColumnName("services");

                    b.HasKey("InstanceId");

                    b.ToTable("instance_status", (string)null);
                });

            modelBuilder.Entity("Gateway.Api.Data.ServiceManifest", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("DesiredStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desired_status");

                    b.Property<string>("Digest")
                        .HasColumnType("text")
                        .HasColumnName("digest");

                    b.Property<string>("EnvSecretRef")
                        .HasColumnType("text")
                        .HasColumnName("env_secret_ref");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IncludeInHealth")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_health");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Name");

                    b.ToTable("service_manifest", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
